-- Order Management System: initial schema.
-- Conventions: uuid PKs generated by the application, `version` for optimistic locking,
-- timestamptz in UTC, money as numeric(12,2) in a single currency (USD).

create table customers (
    id          uuid primary key,
    version     bigint        not null,
    created_at  timestamptz   not null,
    updated_at  timestamptz   not null,
    email       varchar(255)  not null,
    name        varchar(200)  not null,
    phone       varchar(50),
    active      boolean       not null default true
);
create unique index uq_customers_email on customers (lower(email));

create table app_users (
    id            uuid primary key,
    version       bigint       not null,
    created_at    timestamptz  not null,
    updated_at    timestamptz  not null,
    username      varchar(255) not null,
    password_hash varchar(100) not null,
    role          varchar(20)  not null check (role in ('ADMIN', 'STAFF', 'CUSTOMER')),
    customer_id   uuid references customers (id),
    enabled       boolean      not null default true
);
create unique index uq_app_users_username on app_users (lower(username));

create table products (
    id          uuid primary key,
    version     bigint        not null,
    created_at  timestamptz   not null,
    updated_at  timestamptz   not null,
    sku         varchar(64)   not null,
    name        varchar(200)  not null,
    description varchar(2000),
    price       numeric(12,2) not null check (price >= 0),
    active      boolean       not null default true
);
create unique index uq_products_sku on products (upper(sku));

-- One row per product. available = on_hand - reserved.
create table inventory (
    product_id  uuid primary key references products (id),
    version     bigint      not null,
    updated_at  timestamptz not null,
    on_hand     integer     not null check (on_hand >= 0),
    reserved    integer     not null check (reserved >= 0),
    constraint ck_inventory_reserved_le_on_hand check (reserved <= on_hand)
);

create table orders (
    id            uuid primary key,
    version       bigint        not null,
    created_at    timestamptz   not null,
    updated_at    timestamptz   not null,
    customer_id   uuid          not null references customers (id),
    status        varchar(20)   not null
        check (status in ('PENDING', 'PAID', 'SHIPPED', 'DELIVERED', 'CANCELLED', 'REFUNDED')),
    total         numeric(12,2) not null check (total >= 0),
    cancel_reason varchar(500)
);
create index ix_orders_customer on orders (customer_id, created_at desc);
create index ix_orders_status_created on orders (status, created_at);

create table order_items (
    id           uuid primary key,
    order_id     uuid          not null references orders (id),
    product_id   uuid          not null references products (id),
    sku          varchar(64)   not null,
    product_name varchar(200)  not null,
    unit_price   numeric(12,2) not null check (unit_price >= 0),
    quantity     integer       not null check (quantity > 0)
);
create index ix_order_items_order on order_items (order_id);

create table inventory_reservations (
    id         uuid primary key,
    version    bigint      not null,
    created_at timestamptz not null,
    updated_at timestamptz not null,
    order_id   uuid        not null references orders (id),
    product_id uuid        not null references products (id),
    quantity   integer     not null check (quantity > 0),
    status     varchar(20) not null check (status in ('HELD', 'CONSUMED', 'RELEASED'))
);
create index ix_reservations_order on inventory_reservations (order_id);

create table payments (
    id                uuid primary key,
    version           bigint        not null,
    created_at        timestamptz   not null,
    updated_at        timestamptz   not null,
    order_id          uuid          not null references orders (id),
    amount            numeric(12,2) not null check (amount > 0),
    status            varchar(20)   not null check (status in ('SUCCEEDED', 'FAILED')),
    payment_method    varchar(100)  not null,
    gateway_reference varchar(100),
    failure_reason    varchar(255),
    -- sum of PENDING + COMPLETED refunds; the versioned row serialises concurrent refund requests
    refund_committed  numeric(12,2) not null default 0,
    constraint ck_payments_refund_bounds check (refund_committed >= 0 and refund_committed <= amount)
);
create index ix_payments_order on payments (order_id);
-- at most one successful payment per order, enforced by the database
create unique index uq_payments_order_succeeded on payments (order_id) where status = 'SUCCEEDED';

create table refunds (
    id                uuid primary key,
    version           bigint        not null,
    created_at        timestamptz   not null,
    updated_at        timestamptz   not null,
    order_id          uuid          not null references orders (id),
    payment_id        uuid          not null references payments (id),
    amount            numeric(12,2) not null check (amount > 0),
    reason            varchar(500),
    status            varchar(20)   not null check (status in ('PENDING', 'COMPLETED', 'FAILED')),
    gateway_reference varchar(100),
    failure_reason    varchar(255),
    requested_by      varchar(255)  not null
);
create index ix_refunds_order on refunds (order_id);

create table idempotency_keys (
    id            uuid primary key,
    version       bigint       not null,
    created_at    timestamptz  not null,
    updated_at    timestamptz  not null,
    scope         varchar(100) not null,
    idem_key      varchar(200) not null,
    request_hash  varchar(64)  not null,
    resource_type varchar(30)  not null,
    resource_id   uuid         not null,
    constraint uq_idempotency_scope_key unique (scope, idem_key)
);

-- Transactional outbox: written in the same transaction as the state change, relayed to Kafka.
create table outbox_events (
    id           uuid primary key,
    version      bigint       not null,
    created_at   timestamptz  not null,
    updated_at   timestamptz  not null,
    aggregate_id uuid         not null,
    event_type   varchar(60)  not null,
    payload      text         not null,
    published_at timestamptz
);
create index ix_outbox_unpublished on outbox_events (created_at) where published_at is null;

create table audit_logs (
    id          uuid primary key,
    version     bigint        not null,
    created_at  timestamptz   not null,
    updated_at  timestamptz   not null,
    actor       varchar(255)  not null,
    action      varchar(60)   not null,
    entity_type varchar(40)   not null,
    entity_id   varchar(64)   not null,
    details     varchar(2000),
    request_id  varchar(64)
);
create index ix_audit_entity on audit_logs (entity_type, entity_id, created_at desc);
create index ix_audit_created on audit_logs (created_at desc);
